#!/usr/bin/env python3
"""Friday intel-review queue — what Sylvan needs to see, nothing more.

WHY. Sylvan's explicit instruction, 20 Aug 2026: community intel must NEVER
promote itself into ROLE_INTEL.md's machine-readable `setpieces`/
`adjustments` fences automatically. The daily `fpl-daily-intel-sweep` task
only gathers, logs, and drafts narrative (non-machine-readable) entries — it
is not permitted to touch the fences. Promotion happens exactly once a week,
in the `fpl-friday-intel-review` meeting, and only for bites Sylvan
explicitly marks "accepted". This script builds the report that meeting
reads from.

WHAT IT SHOWS, per pending bite:
  - the claim itself (hypothesis, category, falsifiable check, check_by_gw)
  - the suggested model input it would touch, IF accepted (field/op/value —
    same vocabulary as ROLE_INTEL.md's adjustments fence)
  - its resolution status so far (open/confirmed/contradicted/expired) —
    resolution and decision are independent; a still-open bite can still be
    accepted on the strength of its sourcing, same as a Tier-3 override in
    SELECTION_FRAMEWORK.md
  - its SOURCE's track record from score_source_reliability.py — accuracy,
    n, stale_rate — pulled in at review time so the decision is made with
    the same reliability context every time, not from memory

"Pending" = no decision record yet, or its latest decision is "deferred".
Once Sylvan says accept/reject in the review, fpl-friday-intel-review appends
a decision record and the bite drops out of next week's queue.

OUTPUT. docs/data/intel_review_queue.json (machine-readable) and
INTEL_REVIEW.md at the repo root (what the Friday task actually reads from
and shows Sylvan). Regenerate weekly inside fpl-friday-intel-review; do not
hand-edit either output.

    python3 build_intel_review.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
QUEUE_PATH = os.path.join(HERE, "docs", "data", "intel_review_queue.json")
REPORT_PATH = os.path.join(HERE, "INTEL_REVIEW.md")

sys.path.insert(0, HERE)
import score_source_reliability as ssr  # noqa: E402


def pending_bites():
    bites, resolutions, decisions = ssr.load_log()
    gw = ssr._current_gw()
    ranked, _gw2, _n_bites, _n_res = ssr.score()
    by_source = {r["source_name"]: r for r in ranked}

    out = []
    for bid, b in bites.items():
        d = decisions.get(bid)
        if d and d["decision"] in ("accepted", "rejected"):
            continue  # already actioned, not part of the live queue
        status = ssr._status(bid, resolutions, gw)
        src = by_source.get(b.get("source_name", "UNKNOWN"), {})
        out.append({
            **b,
            "status": status,
            "prior_decision": d["decision"] if d else None,
            "source_accuracy": src.get("accuracy"),
            "source_n_resolved": src.get("n_resolved", 0),
            "source_stale_rate": src.get("stale_rate"),
        })
    # Most urgent first: nearest check_by_gw, then oldest first
    out.sort(key=lambda x: (x.get("check_by_gw") or 999, x.get("date", "")))
    return out, gw, ranked


def write_queue(queue, gw):
    os.makedirs(os.path.dirname(QUEUE_PATH), exist_ok=True)
    import datetime as dt
    json.dump(
        {"generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
         "live_gw": gw, "queue": queue},
        open(QUEUE_PATH, "w", encoding="utf-8"), indent=2)


def _fmt_source(b):
    acc = b["source_accuracy"]
    acc_s = f"{acc:.0%}" if acc is not None else f"n={b['source_n_resolved']}, insufficient data"
    return f"{b.get('source_name', 'UNKNOWN')} (tier {b.get('source_tier', '?')}, accuracy {acc_s})"


def render_report(queue, gw, ranked):
    lines = [
        "# Intel review — Friday decision queue",
        "",
        "Generated by `build_intel_review.py`, regenerate weekly — do not "
        "hand-edit. This is the working document for the "
        "`fpl-friday-intel-review` meeting.",
        "",
        f"Live gameweek: {gw if gw is not None else 'unknown'}. "
        f"**{len(queue)} bite(s) awaiting a decision.**",
        "",
        "**Nothing here has touched ROLE_INTEL.md's `setpieces`/`adjustments` "
        "fences, and nothing will until it is explicitly accepted below.** "
        "Accepting a bite is the only path a piece of community intel has "
        "into the numbers `build_squad.py`/`optimise_squad.py` actually "
        "score on.",
        "",
    ]
    if not queue:
        lines.append("*(queue is empty — nothing pending review)*")
    for b in queue:
        adj = ""
        if b.get("field_affected"):
            adj = (f"would set `{b['field_affected']}` "
                   f"{b.get('suggested_op', '?')} {b.get('suggested_value', '?')}"
                   f" (GWs from logging, per ROLE_INTEL.md convention)")
        deferred_note = " — *previously deferred*" if b.get("prior_decision") == "deferred" else ""
        lines += [
            f"## `{b['id']}`{deferred_note}",
            "",
            f"**{b.get('player', '?')}** ({b.get('team', '?')}) — "
            f"{b.get('category', 'other')}, confidence {b.get('confidence', '?')}",
            "",
            f"> {b.get('hypothesis', '')}",
            "",
            f"- Source: {_fmt_source(b)}",
            f"- Logged: {b.get('date', '?')} · Status: **{b['status']}** · "
            f"Falsifiable check by GW{b.get('check_by_gw', '?')}: "
            f"{b.get('falsifiable_check', '')}",
        ]
        if adj:
            lines.append(f"- If accepted: {adj}")
        lines.append("")
    lines += [
        "---",
        "",
        "## Reply with your decisions",
        "",
        "For each bite above, say **accept**, **reject**, or **defer** "
        "(defer = leave it in next week's queue, no action). Only accepted "
        "bites with a `field_affected` get written into ROLE_INTEL.md's "
        "machine-readable fence; accepted bites without one are still logged "
        "as a decision and added to ROLE_INTEL.md's narrative section as "
        "confirmed intel.",
        "",
        "## Source reliability, full picture",
        "",
        "See `SOURCE_RELIABILITY.md` for the complete per-source track "
        "record (all sources, not just those with a bite pending this week).",
        "",
    ]
    if ranked:
        lines += ["| Source | Tier | Accuracy | Resolved | Stale rate |",
                   "|---|---|---|---|---|"]
        for r in ranked:
            acc = f"{r['accuracy']:.0%}" if r["accuracy"] is not None else "insufficient data"
            stale = f"{r['stale_rate']:.0%}" if r["stale_rate"] is not None else "—"
            lines.append(f"| {r['source_name']} | {r['source_tier']} | {acc} | "
                          f"{r['n_resolved']} | {stale} |")
    open(REPORT_PATH, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def main():
    queue, gw, ranked = pending_bites()
    write_queue(queue, gw)
    render_report(queue, gw, ranked)
    print(f"Wrote {QUEUE_PATH} and {REPORT_PATH}")
    print(f"{len(queue)} bite(s) pending review, live GW {gw if gw is not None else 'unknown'}")


if __name__ == "__main__":
    main()
