#!/usr/bin/env python3
"""Does decomposing a player's xG into team output x player share beat the
direct per-90 prior? — the evidence behind METHODOLOGY_ALTERNATIVES.md's
"Team output x player share" section (logged 6 Sep 2026).

Run this before believing anything in that section. Every number quoted there
comes out of this file; nothing was estimated by eye.

    python3 team_share_probe.py

Needs the two archive caches (both gitignored, regenerated by
`fetch_gw_history.py`): `.cache_merged_gw.csv` (2025/26) and
`.cache_merged_gw_2024-25.csv` (2024/25). Exits with a message rather than a
traceback if either is missing.

FIVE CHECKS, and only the last two decide anything:

  A  Is penalty xG inside FPL's `expected_goals`? The proposal is written in
     terms of npxG and claims it comes free with data already pulled.
  B  Ceiling: how much could the decomposition win if it were HANDED the
     target season's real team output? An upper bound no live model reaches.
  C  Is share more persistent season-over-season than the raw rate? The
     proposal's premise requires yes.
  D  How forecastable is team output at all? The decomposition is a product,
     so this term's error passes straight through to the answer.
  E  THE ONE THAT MATTERS — a live-equivalent walk-forward with no
     foreknowledge, scored against the pipeline's own shrinkage
     (scoring.estimate_k_priors / shrink_rate), not a strawman.

SCOPE LIMIT, stated up front because it bounds every conclusion below: this
scores SEASON-HALF aggregates, one split of one season, MID/FWD only. It is
not the per-gameweek walk-forward `historical_backtest_2025_26.py` runs, and
its RMSE figures are NOT comparable to that file's — different denominator,
different population, no cameo gate needed because the aggregation window is
half a season rather than one match. Treat the direction as informative and
the magnitudes as indicative.
"""
import csv, math, os, sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from scoring import estimate_k_priors, shrink_rate, PRIORS_DISPERSION  # noqa: E402

PRIOR_SEASON = os.path.join(HERE, ".cache_merged_gw_2024-25.csv")
TARGET_SEASON = os.path.join(HERE, ".cache_merged_gw.csv")
SPLIT_GW = 20                 # check E: GW1-19 observed, GW20-38 predicted
ATTACKERS = {"MID", "FWD"}
MIN_N90 = 5.0                 # ~450 minutes in each window a player is scored over


def _f(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


def _load(path):
    if not os.path.exists(path):
        sys.exit(f"missing {os.path.basename(path)} — run fetch_gw_history.py first")
    with open(path, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _corr(xs, ys):
    n = len(xs)
    mx, my = sum(xs) / n, sum(ys) / n
    cov = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    vx = sum((x - mx) ** 2 for x in xs)
    vy = sum((y - my) ** 2 for y in ys)
    return cov / math.sqrt(vx * vy) if vx > 0 and vy > 0 else float("nan")


def aggregate(rows):
    """Per-player totals and per-team match output over whatever rows are passed.

    The share denominator is the subtle part. A player's share must be measured
    against the team output that accrued WHILE HE WAS ON THE PITCH, not against
    the team's whole match — otherwise a 20-minute substitute is scored against
    90 minutes of team xG and his share is deflated by construction, which is
    exactly the artifact the proposal says it wants to avoid.

    Two rules follow, and both matter more than they look:

      1. Pro-rate the team's match xG by the player's minutes (mins/90) before
         it enters the denominator. This is an approximation — the archive is
         per-match, so there is no way to know the team's xG in the specific
         minutes he was on — but it is the right BASIS, where the unadjusted
         match total is the wrong one.
      2. Sum numerator and denominator over the window and divide ONCE
         (ratio-of-sums), never average per-match ratios (mean-of-ratios).
         Team xG in a single match is ~1.4 on average but routinely dips near
         0.3, so per-match shares explode above 1.0 and their mean is badly
         biased upward. This is the single easiest way to get the whole idea
         wrong and still produce plausible-looking numbers.
    """
    team_fx = defaultdict(float)
    for r in rows:
        team_fx[(r["team"], r["fixture"])] += _f(r["expected_goals"])

    per = defaultdict(lambda: dict(mins=0.0, xg=0.0, denom=0.0, pos=None))
    team_mins = defaultdict(lambda: defaultdict(float))
    for r in rows:
        m = _f(r["minutes"])
        if m <= 0:
            continue
        p = per[r["name"]]
        p["mins"] += m
        p["xg"] += _f(r["expected_goals"])
        p["denom"] += team_fx[(r["team"], r["fixture"])] * (m / 90.0)
        p["pos"] = r["position"]
        team_mins[r["name"]][r["team"]] += m

    matches = defaultdict(list)
    for (team, _fx), v in team_fx.items():
        matches[team].append(v)
    team_per_match = {t: sum(v) / len(v) for t, v in matches.items()}
    main_team = {n: max(d, key=d.get) for n, d in team_mins.items() if d}
    return per, team_per_match, main_team


def _stats(rows, key):
    n = len(rows)
    err = [r[key] - r["target"] for r in rows]
    mae = sum(abs(e) for e in err) / n
    rmse = math.sqrt(sum(e * e for e in err) / n)
    c = _corr([r[key] for r in rows], [r["target"] for r in rows])
    return mae, rmse, c, sum(err) / n


# ============================================================ A — penalty xG
def check_a(seasons):
    print("=" * 74)
    print("A — is penalty xG inside FPL's `expected_goals`?")
    print("=" * 74)
    for label, rows in seasons:
        missed = [r for r in rows if _f(r.get("penalties_missed")) >= 1]
        if not missed:
            continue
        xgs = sorted(_f(r["expected_goals"]) for r in missed)
        below = sum(1 for x in xgs if x < 0.70)
        print(f"{label}: {len(missed):3d} player-matches containing a missed penalty · "
              f"median xG {xgs[len(xgs)//2]:.2f} · {below} below 0.70")
    print("\nA penalty is worth ~0.76-0.79 xG on its own. If the median in those")
    print("matches sits above that and essentially none fall below 0.70, penalty")
    print("xG is INCLUDED — and npxG cannot be derived from this archive alone.\n")


# ================================================== B/C — ceiling, persistence
def check_bc(rows_prior, rows_target):
    pa, _ta, mta = aggregate(rows_prior)
    pb, tb, mtb = aggregate(rows_target)

    pool = []
    for name, a in pa.items():
        b = pb.get(name)
        if not b or a["pos"] not in ATTACKERS or b["pos"] not in ATTACKERS:
            continue
        n90a, n90b = a["mins"] / 90.0, b["mins"] / 90.0
        if n90a < 2 * MIN_N90 or n90b < MIN_N90 or a["denom"] <= 0:
            continue
        team_now = mtb.get(name)
        if team_now not in tb:
            continue
        pool.append(dict(
            name=name, moved=mta.get(name) != team_now,
            direct=a["xg"] / n90a,
            compos=(a["xg"] / a["denom"]) * tb[team_now],   # perfect foreknowledge
            target=b["xg"] / n90b,
            share_a=a["xg"] / a["denom"], share_b=b["xg"] / b["denom"]))

    print("=" * 74)
    print("B — CEILING: decomposition given the target season's REAL team output")
    print("=" * 74)
    print(f"pool: {len(pool)} MID/FWD, >={2*MIN_N90:.0f} n90 prior season, "
          f">={MIN_N90:.0f} n90 target season")
    print("This is an upper bound. No live model knows next season's team output.\n")

    for label, sel in (("all attackers", pool),
                       ("same club both seasons", [r for r in pool if not r["moved"]]),
                       ("changed club", [r for r in pool if r["moved"]])):
        if len(sel) < 8:
            print(f"{label}: n={len(sel)} — too thin to read\n")
            continue
        md = _stats(sel, "direct")[0]
        mc = _stats(sel, "compos")[0]
        print(f"{label:26s} n={len(sel):3d}  direct MAE {md:.4f}  "
              f"compos MAE {mc:.4f}  -> {(md-mc)/md*100:+.1f}%")

    print()
    print("=" * 74)
    print("C — PERSISTENCE: is share a more stable trait than the raw rate?")
    print("=" * 74)
    for label, sel in (("all", pool),
                       ("same club", [r for r in pool if not r["moved"]]),
                       ("changed club", [r for r in pool if r["moved"]])):
        if len(sel) < 8:
            continue
        cs = _corr([r["share_a"] for r in sel], [r["share_b"] for r in sel])
        cx = _corr([r["direct"] for r in sel], [r["target"] for r in sel])
        print(f"{label:14s} n={len(sel):3d}  corr(share) {cs:.3f}   "
              f"corr(xG90) {cx:.3f}   -> {'share' if cs > cx else 'xG90'} more persistent")
    print("\nThe proposal's premise requires share to be clearly more persistent.\n")


# ========================================================= D — team output
def check_d(seasons):
    print("=" * 74)
    print("D — how forecastable is team attacking output?")
    print("=" * 74)

    def team_series(rows):
        fx, gw = defaultdict(float), {}
        for r in rows:
            k = (r["team"], r["fixture"])
            fx[k] += _f(r["expected_goals"])
            gw[k] = int(r["GW"])
        seq = defaultdict(list)
        for k, v in fx.items():
            seq[k[0]].append((gw[k], v))
        for t in seq:
            seq[t].sort()
        return seq

    series = {label: team_series(rows) for label, rows in seasons}
    labels = list(series)
    if len(labels) == 2:
        sa, sb = series[labels[0]], series[labels[1]]
        both = sorted(set(sa) & set(sb))
        xs = [sum(v for _, v in sa[t]) / len(sa[t]) for t in both]
        ys = [sum(v for _, v in sb[t]) / len(sb[t]) for t in both]
        mae = sum(abs(x - y) for x, y in zip(xs, ys)) / len(both)
        mean_y = sum(ys) / len(ys)
        print(f"season-to-season ({len(both)} teams in both): corr {_corr(xs, ys):.3f}, "
              f"MAE {mae:.3f} xG/match = {mae/mean_y*100:.1f}% of the {mean_y:.2f} mean")

    print("\nnext-match forecast, EWMA of the last 10 vs a flat season-to-date mean:")
    for label, seq in series.items():
        e_ewma, e_flat, tgt = [], [], []
        for vals in ([v for _, v in ms] for ms in seq.values()):
            for i in range(10, len(vals)):
                hist = vals[i - 10:i]
                w = [0.5 ** ((len(hist) - 1 - j) / 4) for j in range(len(hist))]
                e_ewma.append(abs(sum(a * b for a, b in zip(hist, w)) / sum(w) - vals[i]))
                e_flat.append(abs(sum(vals[:i]) / i - vals[i]))
                tgt.append(vals[i])
        m = sum(tgt) / len(tgt)
        ew, fl = sum(e_ewma) / len(e_ewma), sum(e_flat) / len(e_flat)
        print(f"  {label}: EWMA MAE {ew:.3f} ({ew/m*100:.1f}%)   "
              f"flat mean MAE {fl:.3f} ({fl/m*100:.1f}%)   "
              f"-> {'EWMA' if ew < fl else 'FLAT MEAN'} wins")

    allv = [v for seq in series.values() for ms in seq.values() for _, v in ms]
    tm = [sum(v for _, v in ms) / len(ms) for seq in series.values() for ms in seq.values()]
    m, mt = sum(allv) / len(allv), sum(tm) / len(tm)
    sd = math.sqrt(sum((v - m) ** 2 for v in allv) / (len(allv) - 1))
    sdb = math.sqrt(sum((v - mt) ** 2 for v in tm) / (len(tm) - 1))
    print(f"\nsingle-match team xG: mean {m:.2f}, sd {sd:.2f}")
    print(f"season-mean team xG : mean {mt:.2f}, sd {sdb:.2f}")
    print(f"between-team share of single-match variance: {(sdb**2)/(sd**2)*100:.0f}% "
          f"— the rest is match-to-match noise no model recovers.\n")


# ============================================ E — the live-equivalent test
def check_e(rows_prior, rows_target):
    print("=" * 74)
    print(f"E — LIVE-EQUIVALENT walk-forward: predict GW{SPLIT_GW}-38 from "
          f"prior season + GW1-{SPLIT_GW-1}")
    print("=" * 74)
    pa, _ta, _mta = aggregate(rows_prior)
    p1, t1, mt1 = aggregate([r for r in rows_target if int(r["GW"]) < SPLIT_GW])
    p2, _t2, _mt2 = aggregate([r for r in rows_target if int(r["GW"]) >= SPLIT_GW])

    pool = []
    for name, cur in p1.items():
        tgt, prior = p2.get(name), pa.get(name)
        if not tgt or not prior:
            continue
        if cur["pos"] not in ATTACKERS or tgt["pos"] not in ATTACKERS:
            continue
        n90c, n90t, n90p = cur["mins"] / 90.0, tgt["mins"] / 90.0, prior["mins"] / 90.0
        if min(n90c, n90t, n90p) < MIN_N90 or cur["denom"] <= 0 or prior["denom"] <= 0:
            continue
        team = mt1.get(name)
        if team not in t1:
            continue
        pool.append(dict(
            name=name, n90_cur=n90c, raw=cur["xg"] / n90c,
            xg90_prior=prior["xg"] / n90p,
            share_cur=cur["xg"] / cur["denom"],
            share_prior=prior["xg"] / prior["denom"],
            team_fc=t1[team],                       # forecast = observed GW1-19 mean
            target=tgt["xg"] / n90t))

    print(f"pool: {len(pool)} MID/FWD with >={MIN_N90:.0f} n90 in all three windows\n")

    disp = PRIORS_DISPERSION["xg90"]
    k_xg = estimate_k_priors([(r["raw"], r["n90_cur"]) for r in pool], dispersion=disp)
    k_sh = estimate_k_priors([(r["share_cur"], r["n90_cur"]) for r in pool], dispersion=disp)
    print(f"k fitted from the pool's own variance: xG90 {k_xg:.2f} n90, "
          f"share {k_sh:.2f} n90")
    print(f"(the proposal hand-set k = 900 minutes = 10.0 n90 for share)\n")

    for r in pool:
        r["direct"] = shrink_rate(r["raw"], r["n90_cur"], r["xg90_prior"], k_xg)
        r["compos"] = shrink_rate(r["share_cur"], r["n90_cur"],
                                  r["share_prior"], k_sh) * r["team_fc"]
        r["compos_k10"] = shrink_rate(r["share_cur"], r["n90_cur"],
                                      r["share_prior"], 10.0) * r["team_fc"]

    base = _stats(pool, "direct")[0]
    print(f"{'estimator':18s} {'MAE':>8s} {'RMSE':>8s} {'corr':>7s} {'bias':>9s}   vs direct")
    for key, label in (("raw", "raw (current)"), ("direct", "shrunk direct"),
                       ("compos", "compositional"), ("compos_k10", "compos, k=10n90")):
        mae, rmse, c, bias = _stats(pool, key)
        print(f"{label:18s} {mae:8.4f} {rmse:8.4f} {c:7.3f} {bias:+9.4f}   "
              f"{(base-mae)/base*100:+6.1f}%")

    # A margin this small is only meaningful if it is consistent player by
    # player. An MAE that improves while the win rate sits at chance means a
    # few large errors moved, not that the estimator is better.
    wins = sum(1 for r in pool
               if abs(r["compos"] - r["target"]) < abs(r["direct"] - r["target"]))
    n = len(pool)
    tail = sum(math.comb(n, i) for i in range(0, min(wins, n - wins) + 1))
    p = min(1.0, 2 * tail / 2 ** n)
    print(f"\npaired sign test vs shrunk direct: compositional closer on "
          f"{wins}/{n} ({wins/n*100:.1f}%), two-sided p = {p:.3f}")


def main():
    rows_prior, rows_target = _load(PRIOR_SEASON), _load(TARGET_SEASON)
    seasons = [("2024-25", rows_prior), ("2025-26", rows_target)]
    check_a(seasons)
    check_bc(rows_prior, rows_target)
    check_d(seasons)
    check_e(rows_prior, rows_target)


if __name__ == "__main__":
    main()
